fix: add buffer
Level/codec pull request #58
Opened 2020-06-18 15:08 UTC by hugomrdias

This PR adds buffer as a dependency so we don't need to rely on browser bundlers injection.

2020-06-19 08:18 UTC, juliangruber requested changes

2020-06-19 08:18 UTC, juliangruber commented on lib/encodings.js
> +const Buffer = require('buffer').Buffer
this project uses `var` still, for compatibility

2020-06-19 08:19 UTC, juliangruber commented
in general +1 if this makes bundling `level*` easier

2020-06-19 10:53 UTC, juliangruber approved these changes

2020-06-26 07:19 UTC, vweevers commented
This moves the burden - of keeping `buffer` versions in sync across modules - from the bundler to module maintainers. That's fine, `buffer` doesn't change that often.

Some folks (that only use level modules in node) are not happy with additional dependencies. That's OK, because `abstract-leveldown` already has the `buffer` dependency.

I'm still on the fence regarding the webpack change, but that's due to the `nextTick` story (see discussions in `readable-stream`) rather than `buffer`. I do wonder, because we learned that webpack's ideals aren't realistic (which very much applies to the level ecosystem due to its heavy use of streams), whether it's wise to nevertheless continue chasing those ideals. Ultimately a webpack user will still have to inject `nextTick`.

2020-06-26 07:20 UTC, merged

2020-06-26 07:30 UTC, vweevers commented
[9.0.2](https://github.com/Level/codec/releases/tag/v9.0.2)